DEBUG_MODE = True
FLASK_IP = '0.0.0.0'
HOST_MANAGER_PATH = '../builds/hostmanager/hostmanager'
GAME_HOST_PATH = '../builds/gamehost/gamehost'
HOST_MANAGER_PORT = 5005
MAX_GAMES_PER_HOST = 3
SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_MASK_SWAGGER = False
JWT_SECRET_KEY = 'asdfgh'
JWT_ACCESS_TOKEN_EXPIRES = 900  # Value in seconds, 900 seconds equals 15 minutes
JWT_REFRESH_TOKEN_EXPIRES = 86400  # Value in seconds, 86400 seconds equals 24 hours
